### ISSUE TITLE
Prepare the threeten backport for release.

### ISSUE THREAD

**Issue by gkopff** [gkopff/gson-threeten-serialisers#1]
@pdemanget: Is there anything else needed to be done before it can be released?

**Comment by pdemanget** [comment]
Anything seems fine to me: the unit test are passing, and the usage in my project is also OK.

**Comment by gkopff** [comment]
Apologies for taking so long @pdemanget, a bunch of shit cropped up IRL.

**Comment by pdemanget** [comment]
No problem, I can work with a local build.
